name: Il mondo di Funziona
favicon: null
layout_spectrum: 0.5134872449561954
typography_spectrum: 0.8528859154321253
title: Il mondo di Funziona
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7235858899075538
  lightness: 0.06488552177324891
  saturation: 0.7607817077077925
  rhythmicContrast: 0.6177332310471684
purpose: []
