typography_spectrum: 1
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.7607817077077925
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26214
analytics:
  google: null
  facebook: null
  twitter: null
name: Il mondo di Funziona
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Vuoti
    id: 661a49e5-f7a7-4194-9bdb-f6a534cd8e0b
    type: content
favicon: null
title: Il mondo di Funziona
description: Scopri l'improbabile mondo di Funziona
purpose: []
